name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      

      - name: Create unique S3 bucket
        id: create_bucket
        run: |
          BUCKET_NAME="cloud-bucket-1770975946"
          echo "AWS_S3_BUCKET=$BUCKET_NAME" >> $GITHUB_ENV

          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket $BUCKET_NAME already exists"
          else
            echo "Creating bucket $BUCKET_NAME in region $AWS_DEFAULT_REGION"
            if [[ "$AWS_DEFAULT_REGION" == "us-east-1" ]]; then
              aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_DEFAULT_REGION"
            else
              aws s3api create-bucket \
                --bucket "$BUCKET_NAME" \
                --region "$AWS_DEFAULT_REGION" \
                --create-bucket-configuration LocationConstraint="$AWS_DEFAULT_REGION"
            fi
          fi
     
      - name: Upload ./public to S3
        run: |
          echo "Uploading ./public to s3://$AWS_S3_BUCKET/"
          aws s3 sync ./public "s3://$AWS_S3_BUCKET/" 

      - name: Output bucket URL
        run: echo "Deployed to https://$AWS_S3_BUCKET.s3.amazonaws.com/"
